---
title: 'Course Structure'
---

## About me

- Adi Cilik Pierewan
- Data enthusiast
- Lecturer at Universitas Negeri Yogyakarta
- Advisor at KONEKSI


## About the course

- The course is divided into two parts: theoretical and practical. 
- In the theoretical section, we discuss the theoretical assumption and underlying multilevel model. 
- In the practical section, we explore, dive, and estimate the multilevel model. 
- The course will focus on the two-level linear model as a template to illustrate the issues of specification, estimation, and inference. 
- Although each lesson includes guided exercises using R, no prior knowledge of R is required.


## Course approach

- Learn the intuition of modeling
- Hands-on experience
- Worked example 

## Structure
            
-  Regression
-  Why MLM?
-  Hands-on Null Model
-  Random Intercept
-  Hands-on Random Intercept
-  Random Slope
-  Hands-on Random Slope

## Carpentry tools

- [R](https://cran.r-project.org/bin/windows/base/) 
- [RStudio](https://posit.co/downloads/)

## The packages

- [`tidyverse`](https://www.tidyverse.org/)
- [`lme4`](https://cran.r-project.org/web/packages/lme4/index.html)
