---
title: 'Multilevel Model'
teaching: 10
exercises: 2
---

:::::::::::::::::::::::::::::::::::::: questions 

- How do you write a lesson using R Markdown and `{sandpaper}`?

::::::::::::::::::::::::::::::::::::::::::::::::

::::::::::::::::::::::::::::::::::::: objectives

- Explain how to use markdown with the new lesson template
- Demonstrate how to include pieces of code, figures, and nested challenge blocks

::::::::::::::::::::::::::::::::::::::::::::::::

## Introduction

Given that data in social sciences are naturally nested, we need to address such a structure in which individuals are nested within families, neighborhoods, schools, and geographical areas. The course will provide an understanding of the concepts of the multilevel model and its application in social sciences.

The course is divided into two parts: theoretical and practical. In the theoretical section, we discuss the theoretical assumption and underlying multilevel model. In the practical section, we explore, dive, and estimate the multilevel model. Two elective case studies will be provided in this course: the multilevel model in education, where students are clustered into schools. Another application is the analysis of cross-country data, such as the World Values Survey, while the second concerns values and attitudes worldwide, considering individual and country-specific characteristics. The course will focus on the two-level linear model as a template to illustrate the issues of specification, estimation, and inference. Although each lesson includes guided exercises using R, no prior knowledge of R is required.

## About the course

- The course is divided into two parts: theoretical and practical. 
- In the theoretical section, we discuss the theoretical assumption and underlying multilevel model. 
- In the practical section, we explore, dive, and estimate the multilevel model. 
- The course will focus on the two-level linear model as a template to illustrate the issues of specification, estimation, and inference. 
- Although each lesson includes guided exercises using R, no prior knowledge of R is required.


## Course approach

- Learn the intuition of modeling
- Hands-on experience
- Worked example 

## Structure
            
-  Regression
-  Why MLM?
-  Hands-on Null Model
-  Random Intercept
-  Hands-on Random Intercept
-  Random Slope
-  Hands-on Random Slope

## Carpentry tools

- [R](https://cran.r-project.org/bin/windows/base/) 
- [RStudio](https://posit.co/downloads/)

## The packages

- [`tidyverse`](https://www.tidyverse.org/)
- [`lme4`](https://cran.r-project.org/web/packages/lme4/index.html)
